apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: postgres-secret
  namespace: dev

spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: postgres-secret
        property: username

    - secretKey: password
      remoteRef:
        key: postgres-secret
        property: password

    - secretKey: dbname
      remoteRef:
        key: postgres-secret
        property: dbname