ingress:
  controller:
    service:
      type: ClusterIP

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    config:
      hsts: "true"
      hsts-max-age: "15768000"
      hsts-include-subdomains: "true"
      hsts-preload: "true"