apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: postgres-password
  namespace: dev

spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: postgres-password
    creationPolicy: Owner

  data:
    - secretKey: postgres
      remoteRef:
        key: postgres-password
        property: postgres

    - secretKey: nextcloud
      remoteRef:
        key: postgres-password
        property: nextcloud

