apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: postgresql-secret
  namespace: external-secrets

spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: postgresql-secret
    creationPolicy: Owner

  data:
    - secretKey: postgresql-username
      remoteRef:
        key: postgresql-secret
        property: username

    - secretKey: postgresql-password
      remoteRef:
        key: postgresql-secret
        property: password

    - secretKey: postgresql-adminpassword
      remoteRef:
        key: postgresql-secret
        property: adminpassword
