name: Docker image

on:
  push:
    branches: 
      - main
    paths:
      - "images/postgres-backup/**"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{ secrets.ECR_ROLE }}
          aws-region: ap-southeast-1

      - uses: aws-actions/amazon-ecr-login@2

      - uses: docker/build-push-action@v6
        with:
          context: ./images/postgres-backup
          push: true
          tags: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/postgres-backup:${{ github.sha }}


#this pipeline my design,is not ai